version: '2'

run:
  timeout: 3m

formatters:
  enable:
    - goimports

issues:
  # Disable limits on the number of printed issues
  max-issues-per-linter: 0    # 0 = no limit
  max-same-issues: 0          # 0 = no limit

linters:
  default: all

  disable:
    - dupl      # Dupl is disabled, since we're generating a lot of boilerplate code.
    - cyclop    # Cyclop is disabled, since cyclomatic complexities is very abstract metric,
                # that sometimes lead to strange linter behaviour.
    - wsl       # WSL is disabled, since it's obsolete. Using WSL_v5.
    - nlreturn  # nlreturn is disabled, since it's duplicated by wsl_v5.return check.
    - ireturn   # ireturn is disabled, since it's not needed.
    - godox     # godox is disabled to allow TODO comments for unimplemented functionality.
    - gocognit  # gocognit is disabled, cognitive complexity is too restrictive.
    - gocyclo   # gocyclo is disabled, cyclomatic complexities is very abstract metric,
                # that sometimes lead to strange linter behaviour.
    - funlen    # funlen is disabled, function length limits are too restrictive.
    - maintidx  # maintidx is disabled, purpose of this metric is unknown.

  exclusions:
    generated: lax
    rules:
      - path: _test.go
        linters:
          - wrapcheck

  settings:
    varnamelen:
      ignore-names:
        - tt
        - ok
        - tb
        - i
        - m
      ignore-decls:
        - mc *minimock.Controller
        - t T
    godot:
      scope: all
    lll:
      line-length: 120
      tab-width: 4
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      case-max-lines: 0
      default: all
    depguard:
      rules:
        main:
          files:
            - "$all"
            - "!$test"
          allow:
            - $gostd
            - "github.com/shoenig/test"
            - "go.yaml.in/yaml/v3"
            - "github.com/tarantool/go-config"
        test:
          files:
            - "$test"
          allow:
            - $gostd
            - "github.com/shoenig/test"
            - "github.com/stretchr/testify"
            - "github.com/tarantool/go-config"
